### ISSUE TITLE
Default sort config does not support buffers with commas in their name

### ISSUE THREAD

**Issue by symphorien** [de-vri-es/weechat-autosort#13]
The default sort config contains `${info:autosort_replace,#,,${buffer.name}}` in the `hashless_name` helper.
If a buffer contains a comma in its name, then `info:autosort_replace` is given more than three parameter and an error is displayed: `autosort: usage: ${info:autosort_replace,old,new,text}`
I could not find any reliable way to escape the comma.

**Comment by de-vri-es** [comment]
hmm, interesting. In this case the replace function could stop treating comma's special after the third one. But that won't work for `${info:autosort_order,...}`.

The biggest problem here is that the info hook only sees the expanded string. Ideally the expansion would occur after argument splitting, but thats not how weechat eval strings work. It is possible to add another info hook that escapes commas. Not very nice, but it would seem that it is necessary.

**Comment by de-vri-es** [comment]
There is now a workaround available in master with the addition of `${info:autosort_escape,...}`. Will submit a PR to the scripts repository shortly.

Sorry for the long wait, but thanks for reporting the issue!
