### ISSUE TITLE
'/help autosort' missing explanation of newer '${info:}' options

### ISSUE THREAD

**Issue by demure** [de-vri-es/weechat-autosort#16]
It appears that at least two of the newer `${info:}` helper variables are not documented/explained in the output of `/help autosort`, leaving newer users to discover their existence from the embedded changelog in the script, and to divine the correct usage of these variables on their own.

> 3.5:
>   \* Add ${info:autosort_escape,...} to escape arguments for other info hooks.
> ...
> 3.0:
> ...
>   \* Add ${info:autosort_order,value,first,second,third} to ease writing sort rules.

**Comment by de-vri-es** [comment]
Right, good point, thanks for reporting. I'll try to fix this before the end of the week.

**Comment by de-vri-es** [comment]
PR submitted at the scripts repo: https://github.com/weechat/scripts/pull/343

Thanks again for reporting :)
