### ISSUE TITLE
Getting lots of these in my logs after recent host upgrade

### ISSUE THREAD

**Issue by seitzbg** [de-vri-es/weechat-autosort#17]
autosort: usage: ${info:autosort_replace,old,new,text}
autosort: usage: ${info:autosort_replace,old,new,text}
autosort: usage: ${info:autosort_replace,old,new,text}
autosort: usage: ${info:autosort_replace,old,new,text}
autosort: usage: ${info:autosort_replace,old,new,text}

Please advise!

**Comment by pmodin** [comment]
Had the same issue, removed `autosort.conf` to let the plugin recreate it. Diff was trivial as I hadn't modified the file. Solved it for me.

**Comment by de-vri-es** [comment]
The most likely cause is commas in buffer names without the new escaping in rules. You shoul make sure you're using autosort 3.6, and then you can update the helper variables to the default. That should fix the error.

If you have custom helpers, you can manually add `${info:autosort_escape,...}` around the problem bit. The updated `hashless_name` helper looks like this in the new default config: `${info:autosort_replace,#,,${info:autosort_escape,${buffer.name}}}`

**Comment by de-vri-es** [comment]
@seitzbg: Could you confirm if the suggestions above resolve your issue?

**Comment by hv15** [comment]
I didn't have any custom rules so I followed @pmodin suggestion, this has resolved the issue for me.

**Comment by de-vri-es** [comment]
Good to hear. Thanks for reporting back!

**Comment by apetresc** [comment]
@de-vri-es I _did_ have rules that I wanted to keep, so I didn't want to just completely nuke my `autosort.conf`.

Thankfully, your suggestion to manually wrap `{$buffer.name}` with an `${info:autosort_replace}` was exactly the right solution; as in #720, the problem (which I think lots of people are encountering) is that group chats in wee-slack are being formatted as hashless `@user1,user2,user3` buffers, so the `hashless` was indeed the right block to apply the fix in.

Thanks so much for the very accurate diagnosis!

**Comment by de-vri-es** [comment]
Glad to hear it :)

Note that you probably meant `${info:autosort_escape}` instead of `${info:autosort_replace}` ;)

**Comment by apetresc** [comment]
Yes sorry, that's what I meant/did!
