### ISSUE TITLE
issue with latest wee-slack

### ISSUE THREAD

**Issue by dyipon** [de-vri-es/weechat-autosort#19]
Hi,

I just updated to the [latest ](https://github.com/wee-slack/wee-slack/commit/de5eb518fda26fed3b5cd41c20b064c04020bbb9) [wee-slack](https://github.com/wee-slack/wee-slack) , but autosort script stopped to working.
Is there any workaround or fix? 

Thanks

**Comment by de-vri-es** [comment]
I'd love to help, but you're going to have to be more specific. I just updated to `slack.py` 2.6.0 from the built-in script manager and `autosort.py` still seems to work fine.

What exactly is broken? What did you expect to happen, but what happens instead? Are there any error messages?

**Comment by dyipon** [comment]
well, I tried with latest (but not yet released) weechat, nor with 2.6.0. 
after I downgrade back to 2.6.0, it works again.

**Comment by de-vri-es** [comment]
Could you still elaborate on what you mean with "not working"? Since `wee-slack` isn't released yet, there is time to fix the problem before it hits the official script repository. But then I would really need to know what the problem is.

**Comment by dyipon** [comment]
I just enabled the autosort.sorting.debug_log, and tried to get any error messages, but no success. No errors, no notices, the only thing I see is the channels are un-ordered.
I tried the manual /autosort, and got this: 'weechat | autosort: Finished sorting buffers in 0.0121 seconds.'
But buffer names remained in place.

A few lines from debug messages:
```
            │0044            weechat | autosort: debug: Signal received during sort limit timeout, starting queued sort.
            │0044            weechat | autosort: debug: Finished sorting buffers in 0.0482 seconds.
            │0044            weechat | autosort: debug: Starting sort limit timeout of 100 ms.
            │0044            weechat | autosort: debug: Sort limit timeout expired without receiving a signal.
            │0044            weechat | autosort: debug: Signal buffer_renamed received, starting signal delay timeout of 5 ms.
            │0044            weechat | autosort: debug: Signal delay timeout expired, starting sort.
            │0044            weechat | autosort: debug: Finished sorting buffers in 0.0130 seconds.
            │0044            weechat | autosort: debug: Starting sort limit timeout of 100 ms.
            │0044            weechat | autosort: debug: Sort limit timeout expired without receiving a signal.
            │0044            weechat | autosort: debug: Signal buffer_opened received, starting signal delay timeout of 5 ms.
            │0044            weechat | autosort: debug: Signal delay timeout expired, starting sort.
            │0044            weechat | autosort: debug: Finished sorting buffers in 0.0133 seconds.
            │0044            weechat | autosort: debug: Starting sort limit timeout of 100 ms.
            │0044            weechat | autosort: debug: Sort limit timeout expired without receiving a signal.
            │0046            weechat | autosort: Finished sorting buffers in 0.0131 seconds.
            │0046            weechat | autosort: Finished sorting buffers in 0.0132 seconds.
            │0046            weechat | autosort: Finished sorting buffers in 0.0135 seconds.
            │0046            weechat | autosort: debug: Signal buffer_opened received, starting signal delay timeout of 5 ms.
            │- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            │0046            weechat | autosort: debug: Signal delay timeout expired, starting sort.
            │0046            weechat | autosort: debug: Finished sorting buffers in 0.0135 seconds.
            │0046            weechat | autosort: debug: Starting sort limit timeout of 100 ms.
            │0046            weechat | autosort: debug: Sort limit timeout expired without receiving a signal.
            │0047            weechat | autosort: Finished sorting buffers in 0.0127 seconds.
            │0047            weechat | autosort: /autosort help: command not found
            │0047            weechat | autosort: /autosort ?: command not found
            │0047            weechat | autosort: Finished sorting buffers in 0.0121 seconds.

```

**Comment by de-vri-es** [comment]
Thanks for the info. I suspect `weeslack` removed some buffer variables that are used for sorting. I will try to investigate.

**Comment by de-vri-es** [comment]
I tested with the latest version from https://github.com/wee-slack/wee-slack and it still works as expected for me with the default rules.

Do you have non-default rules by any chance? If the problem persists, can post your rules and helper variables as shown by `/autosort rules` and `/autosort helpers`?

**Comment by dyipon** [comment]
I just leeched the latest version of wee-slack, but no lock.

Here are my rules:
            │0904            weechat | autosort: Sorting rules:
            │0904            weechat |     0: ${if:${buffer.full_name}!=python.xxx.slack.com.#xx}
            │0904            weechat |     1: ${if:${buffer.full_name}!=python.xxxx.slack.com.&xxxx}
            │0904            weechat |     2: ${if:${buffer.full_name}!=irc.bitlbee.dogsie}
            │0904            weechat |     3: ${if:${buffer.full_name}!=python.yyy.slack.com.yyy}
            │0904            weechat |     4: ${if:${buffer.full_name}!=python.yyy.slack.com.tyyyy}
            │0904            weechat |     5: ${if:${buffer.full_name}!=python.yyy.slack.com.&mobil}


            │0906            weechat | autosort: Helper variables:
            │0906            weechat |        core_first: ${if:${buffer.full_name}!=core.weechat}
            │0906            weechat |     hashless_name: ${info:autosort_replace,#,,${buffer.name}}
            │0906            weechat |         irc_first: ${if:${buffer.plugin.name}!=irc}
            │0906            weechat |          irc_last: ${if:${buffer.plugin.name}==irc}
            │0906            weechat |     irc_raw_first: ${if:${buffer.full_name}!=irc.irc_raw}
            │0906            weechat |      irc_raw_last: ${if:${buffer.full_name}==irc.irc_raw}

**Comment by de-vri-es** [comment]
Ah, I see. It looks like wee-slack renamed their buffers to `python.slack.$workspace.$channel`. The new naming scheme does seem more logical.

You'll have to update your custom rules to match.

**Comment by dyipon** [comment]
Thanks for your help, It's working perfectly.

**Comment by de-vri-es** [comment]
My pleasure, and glad to hear :)
